version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /admin-web
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /live-dashboard
    schedule:
      interval: weekly
