import { FormEvent, useEffect, useMemo, useState } from 'react';
import { api } from '../api';
import type { CatalogItem, Client, Quote, QuoteStatus, Vehicle } from '../types';

type DraftItem={catalogItemId:string;quantity:number};
export function Quotes(){
  const [quotes,setQuotes]=useState<Quote[]>([]),[clients,setClients]=useState<Client[]>([]),[vehicles,setVehicles]=useState<Vehicle[]>([]),[catalog,setCatalog]=useState<CatalogItem[]>([]),[error,setError]=useState('');
  const [clientId,setClientId]=useState(''),[vehicleId,setVehicleId]=useState(''),[discountPct,setDiscountPct]=useState(0),[validityDays,setValidityDays]=useState(15),[items,setItems]=useState<DraftItem[]>([{catalogItemId:'',quantity:1}]);
  async function load(){try{const [q,c,v,k]=await Promise.all([api<Quote[]>('/quotes'),api<Client[]>('/clients'),api<Vehicle[]>('/vehicles'),api<CatalogItem[]>('/catalog')]);setQuotes(q);setClients(c.filter(x=>x.active));setVehicles(v);setCatalog(k.filter(x=>x.active));if(!clientId&&c[0])setClientId(c[0].id);}catch(e){setError(msg(e));}}
  useEffect(()=>{void load();},[]); const allowedVehicles=useMemo(()=>vehicles.filter(v=>v.clientId===clientId),[vehicles,clientId]);
  useEffect(()=>{if(!allowedVehicles.some(v=>v.id===vehicleId))setVehicleId(allowedVehicles[0]?.id??'');},[clientId,vehicles]);
  async function create(e:FormEvent){e.preventDefault();setError('');try{const clean=items.filter(x=>x.catalogItemId);if(!clientId||!vehicleId||!clean.length)throw new Error('Seleccione cliente, vehículo y al menos un ítem');await api('/quotes',{method:'POST',body:JSON.stringify({clientId,vehicleId,discountPct,validityDays,items:clean})});setItems([{catalogItemId:'',quantity:1}]);await load();}catch(err){setError(msg(err));}}
  async function status(id:string,next:QuoteStatus){try{await api(`/quotes/${id}/status`,{method:'PATCH',body:JSON.stringify({status:next})});await load();}catch(e){setError(msg(e));}}
  async function workOrder(id:string){try{await api(`/work-orders/from-quote/${id}`,{method:'POST'});await load();}catch(e){setError(msg(e));}}
  return <><section className="section-heading"><div><p className="eyebrow">Ventas y aprobación</p><h2>Cotizaciones</h2></div></section>{error&&<div className="alert error">{error}</div>}
  <form className="panel form-grid" onSubmit={create}><h3 className="full">Nueva cotización</h3><label>Cliente<select value={clientId} onChange={e=>setClientId(e.target.value)}>{clients.map(c=><option key={c.id} value={c.id}>{c.fullName}</option>)}</select></label><label>Vehículo<select value={vehicleId} onChange={e=>setVehicleId(e.target.value)}>{allowedVehicles.map(v=><option key={v.id} value={v.id}>{v.plate} · {v.make} {v.model}</option>)}</select></label><label>Descuento %<input type="number" min="0" max="100" value={discountPct} onChange={e=>setDiscountPct(Number(e.target.value))}/></label><label>Vigencia (días)<input type="number" min="1" max="90" value={validityDays} onChange={e=>setValidityDays(Number(e.target.value))}/></label>
    <div className="full quote-lines"><h4>Ítems</h4>{items.map((item,index)=><div className="line" key={index}><select value={item.catalogItemId} onChange={e=>setItems(items.map((x,i)=>i===index?{...x,catalogItemId:e.target.value}:x))}><option value="">Seleccione producto/servicio</option>{catalog.map(x=><option key={x.id} value={x.id}>{x.sku} · {x.name} · ${Number(x.price).toFixed(2)}</option>)}</select><input type="number" min="0.01" step="0.01" value={item.quantity} onChange={e=>setItems(items.map((x,i)=>i===index?{...x,quantity:Number(e.target.value)}:x))}/><button type="button" className="ghost" onClick={()=>setItems(items.filter((_,i)=>i!==index))}>×</button></div>)}<button type="button" onClick={()=>setItems([...items,{catalogItemId:'',quantity:1}])}>+ Agregar ítem</button></div><div className="full"><button className="primary">Crear cotización</button></div></form>
  <section className="panel"><div className="table-wrap"><table><thead><tr><th>Número</th><th>Cliente / vehículo</th><th>Total</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{quotes.map(q=><tr key={q.id}><td className="mono">{q.number}</td><td><strong>{q.client?.fullName}</strong><small>{q.vehicle?.plate} · vence {new Date(q.expiresAt).toLocaleDateString()}</small></td><td>${Number(q.total).toFixed(2)}<small>Desc. {Number(q.discountPct)}%</small></td><td><span className={`badge ${q.status==='approved'?'success':q.status==='rejected'||q.status==='expired'?'danger':'neutral'}`}>{q.status}</span></td><td className="actions">{q.status==='draft'&&<button onClick={()=>status(q.id,'sent')}>Enviar</button>}{['draft','sent'].includes(q.status)&&<button onClick={()=>status(q.id,'approved')}>Aprobar</button>}{['draft','sent'].includes(q.status)&&<button onClick={()=>status(q.id,'rejected')}>Rechazar</button>}{q.status==='approved'&&<button className="primary compact" onClick={()=>workOrder(q.id)}>Crear OT</button>}</td></tr>)}</tbody></table></div></section></>;
}
const msg=(e:unknown)=>e instanceof Error?e.message:'Error inesperado';
